### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'debug'

### ISSUE THREAD

**Issue by Minoski85** [AmadeusITGroup/JumpSSH#109]
Hi friends,
I'm a beginner with programming, I hope someone can help me.
I installed python on windows 10.
(netmiko_project) C: \ Users \ GSPECIA \ netmiko_project \ Scripts> python --version
Python 3.8.2

I would like to connect to a router using a bridge machine and I am trying to use the jumpssh library, but something is not working:

from jumpssh import SSHSession
from getpass import getpass

password = getpass ()

gateway_session = SSHSession ("10.178.6.68", "user", password = password) .open ()
print (gateway_session)

remote_session = gateway_session.get_remote_session ("1.244.243.213", password = password)

If I try to launch the script, I get the following message:

(netmiko_project) C: \ Users \ GSPECIA \ netmiko_project \ Scripts> python jumphost.py
Password:
SSHSession (host = 10.178.6.68, username = gspecia, port = 22, private_key_file = None, proxy_transport = None)
Exception ignored in: <function SSHSession._del_ at 0x000001A362DC3AF0>
Traceback (most recent call last):
  File "C: \ Users \ GSPECIA \ netmiko_project \ lib \ site-packages \ jumpssh \ session.py", line 89, in _del_
  File "C: \ Users \ GSPECIA \ netmiko_project \ lib \ site-packages \ jumpssh \ session.py", line 196, in close
  File "C: \ Users \ GSPECIA \ netmiko_project \ lib \ site-packages \ jumpssh \ session.py", line 198, in close
AttributeError: 'NoneType' object has no attribute 'debug'
Exception ignored in: <function SSHSession._del_ at 0x000001A362DC3AF0>
Traceback (most recent call last):
  File "C: \ Users \ GSPECIA \ netmiko_project \ lib \ site-packages \ jumpssh \ session.py", line 89, in _del_
  File "C: \ Users \ GSPECIA \ netmiko_project \ lib \ site-packages \ jumpssh \ session.py", line 198, in close
AttributeError: 'NoneType' object has no attribute 'debug'

(netmiko_project) C: \ Users \ GSPECIA \ netmiko_project \ Scripts>

What could be causing this problem?

If I connect normally through cmd everything works:

(netmiko_project) C: \ Users \ GSPECIA \ netmiko_project \ Scripts> ssh jumphost

************************************************** *****************************
Password:
Last login: Wed Apr 15 11:56:50 2020 from 10.133.207.1
Last login: Wed Apr 15 11:56:50 2020 from 10.133.207.1

Type xterm-256color unknown
                                                                                                                        $
ssh 1,244,243,213
user@1.244.243.213's password:

  -------------------------------------------------- ---------------------------
  User last login information:
  -------------------------------------------------- ---------------------------
  Access Type: SSH
   -------------------------------------------------- ---------------------------
<8843RMCPE9>

Thanks in advance to all,
Girolamo

**Comment by t-cas** [comment]
Hi @Minoski85,

Thanks for reporting this issue. It seems to happen during automated closure of SSHSession handled during python garbage collection, there is probably something to improve in jumpssh code for that.
Can you try to explicitly close your session at the end of you script (or with context manager), using:

    gateway_session.close()

it will automatically also close the child session (remote_session) and should fix your issue.

**Comment by Minoski85** [comment]
Hi Thibaud,
it works!
(I have added also a print of the remote_connection, to verify that the connection is ok):

C:\Users\USER\netmiko_project\Scripts>python jumphost.py
Password:
SSHSession(host=10.178.6.68, username=user, port=22, private_key_file=None, proxy_transport=None)
SSHSession(host=1.244.243.213, username=user, port=22, private_key_file=None, proxy_transport=<paramiko.Transport at 0x7c9f4d30 (cipher aes128-ctr, 128 bits) (active; 1 open channel(s))>)
C:\Users\USER\netmiko_project\Scripts>

Thanks very much!

**Comment by t-cas** [comment]
Delivered in release [1.6.4](https://github.com/AmadeusITGroup/JumpSSH/releases/tag/1.6.4)
