### ISSUE TITLE
only part of the command is executed on remote server

### ISSUE THREAD

**Issue by rajeshbadveti** [AmadeusITGroup/JumpSSH#113]
Hi Team,

I have the below issue where the complete command is not executed or the expected output is not returned - please can you let us know what is wrong and how to overcome this ?
I wont be able to use get_cmd_output function because I will have to pass the param username: (user used to execute the command) as well.

Two commands passed as list to run_cmd:
1. source rc-core 
2. nova list --fields id,name,host,status  | grep -w compute-1 | awk '{print $2}'

Expected output:
000b5774-105f-4569-8d71-9e5f4c49d2d6

Actual output:
DEBUG:root:output.output: | 000b5774-105f-4569-8d71-9e5f4c49d2d6 | 100-DEPLOYM_s2_0_b34c4ed9-742c-45f5-9eda-767120a9902e     | compute-1.localdomain     | ACTIVE |

debug logs:
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) successful!
INFO:jumpssh.session:Successfully connected to 'x.x.x.x:22'
DEBUG:jumpssh.session:Running command 'source rc-core && nova list --fields id,name,host,status  | grep -w compute-1 | awk '{print $2}'' on 'x.x.x.x' as stack...
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] EOF received (0)
DEBUG:paramiko.transport:[chan 0] EOF sent (0)
DEBUG:jumpssh.session:Closing connection to 'x.x.x.x:22'...
DEBUG:paramiko.transport:[chan 4] EOF sent (4)
DEBUG:paramiko.transport:EOF in transport thread
DEBUG:root:output.output: | 000b5774-105f-4569-8d71-9e5f4c49d2d6 | 100-DEPLOYM_s2_0_b34c4ed9-742c-45f5-9eda-767120a9902e     | compute-1.localdomain     | ACTIVE |
INFO:jumpssh.session:Connecting to 'x.x.x.x:22' through 'localhost' with user 'root'...
DEBUG:paramiko.transport:[chan 5] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 5] Max packet out: 32768 bytes

Also I have tried similar test using the below sample script on a different server, where I have created a file manually with the information that would return by the "nova list --fields id,name,host,status" command, filename: git.log
This test returns the expected output without any problem

```
import logging
from jumpssh import SSHSession
logging.basicConfig(filename="github_magics_debug_output.log", level=logging.DEBUG)

GATEWAY_SESSION = SSHSession('localhost', 'user1', password='pass1', port=40022).open()

REMOTE_SESSION = GATEWAY_SESSION.get_remote_session('x.x.x.x', 'user2', password='pass2')

OUTPUT = REMOTE_SESSION.run_cmd("cat git.log | grep -w compute-1 | awk '{print $2}'")

logging.debug("output.output: {}" .format(str(OUTPUT.output)))

print OUTPUT.output
```

output:
000b5774-105f-4569-8d71-9e5f4c49d2d6

Debug log:
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) successful!
INFO:jumpssh.session:Successfully connected to 'x.x.x.x:22'
DEBUG:jumpssh.session:Running command 'cat git.log | grep -w compute-1 | awk '{print $2}'' on 'x.x.x.x' as root...
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] EOF received (0)
DEBUG:paramiko.transport:[chan 0] EOF sent (0)
DEBUG:root:output.output: 000b5774-105f-4569-8d71-9e5f4c49d2d6
DEBUG:paramiko.transport:EOF in transport thread
DEBUG:paramiko.transport:EOF in transport thread

Appreciate your support.

**Comment by rajeshbadveti** [comment]
Another example of same issue, below is the command prepared with HOST_SERVER_NAME is passed as COMPUTE-1

snippet of the code:
`custom_commands_dict['HOST_SERVER_CIMC_NAME_CMD'] = ["source stackrc", "openstack server list | grep -w" + ' ' + str(var_dict['HOST_SERVER_NAME'].lower()) + ' ' + "| awk '{print $2}' | xargs openstack baremetal node show --instance -f json | jq '.instance_info.display_name,.driver_info.ipmi_address' | tail -2 | head -1 | sed 's/\"//g'"]`


debug log:
INFO:jumpssh.session:Successfully connected to 'x.x.x.x:22'
DEBUG:jumpssh.session:Running command 'source rc-core && source stackrc && openstack server list | grep -w compute-1 | awk '{print $2}' | xargs openstack baremetal node show --instance -f json | jq '.instance_info.display_name,.driver_info.ipmi_address' | tail -2 | head -1 | sed 's/"//g'' on 'x.x.x.x' as stack...
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] EOF received (0)
DEBUG:paramiko.transport:[chan 0] EOF sent (0)
DEBUG:jumpssh.session:Closing connection to 'x.x.x.x:22'...
DEBUG:paramiko.transport:[chan 4] EOF sent (4)
DEBUG:root:output.output: usage: openstack baremetal node show [-h] [-f {json,shell,table,value,yaml}]
                                     [-c COLUMN] [--max-width <integer>]
                                     [--noindent] [--prefix PREFIX]
                                     [--instance]
                                     [--fields <field> [<field> ...]]
                                     <node>
openstack baremetal node show: error: unrecognized arguments: 587add15-29b8-4db3-bd6a-954501a2c465 | compute-1 | ACTIVE | ctlplane=192.200.0.121 | overcloud-full |
INFO:jumpssh.session:Connecting to 'x.x.x.x:22' through 'localhost' with user 'root'...


when manually executed, we get the below output. It seemed like the awk part did not execute on remote server and caused change in the args that resulted in the "error: unrecognized arguments:"

[stack@ospd ~]$ openstack server list | grep -w compute-1
| 587add15-29b8-4db3-bd6a-954501a2c465 | compute-1     | ACTIVE | ctlplane=192.200.0.121 | overcloud-full |
[stack@ospd ~]$ 


I wrote another sample piece of code just to test this and it seem to be working fine
```
import logging
from jumpssh import SSHSession
logging.basicConfig(filename="github_magics_debug_output.log", level=logging.DEBUG)

HOST_SERVER_NAME = 'COMPUTE-1'
GATEWAY_SESSION = SSHSession('localhost', 'user', password='pass', port=40022).open()

REMOTE_SESSION = GATEWAY_SESSION.get_remote_session('10.248.121.209', 'user1', password='pass1')

OUTPUT = REMOTE_SESSION.run_cmd(["source stackrc", "openstack server list | grep -w" + ' ' +  HOST_SERVER_NAME.lower() + ' ' + "| awk '{print $2}' | xargs openstack baremetal node show --instance -f json | jq '.instance_info.display_name,.driver_info.ipmi_address' | tail -2 | head -1 | sed 's/\"//g'"])
logging.debug("output.output: {}" .format(str(OUTPUT.output)))

print OUTPUT.output
```

**Comment by t-cas** [comment]
Hello,

For you first comment, your test code gives you the answer: if output of nova command is right, you get your expected output. Did you verify output returned by nova is what you expect ?

For your second comment, it seems more an issue with the bash command itself given the "unrecognized arguments" error, I suggest you try with smaller command and check each output, to try to pinpoint where the issue comes from, then add more pipes when output seems ok to you.

I cannot see anything specific to jumpssh issue here, I hope this answer still helps.

**Comment by rajeshbadveti** [comment]
Hello
I agree this is not an issue with jumpssh. Even the command framed using the string + variables is fine. However I observed that it is the command can get executed until you have the "string + variable1..n"

However when I add "string1 + variable1..n + string2", it could only execute the part of it
"string1 + variable1..n" leaving behind the string2.

I am using python 2.7 and trying to see if there is a way to overcome this - any help is appreciated.

**Comment by rajeshbadveti** [comment]
I was able to understand the problem.
All I had to do is to add "\" before "$" symbol

For example:
awk '{print \$2}'

Now it works fine, , hope this will help others.
