### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by netengpy** [AmadeusITGroup/JumpSSH#117]
Hi
I am getting authentication error when ssh to Cisco router. Credentials are correct.
ssh to windows 10 machine works fine.

`omz@mac ~ % ssh developer@ios-xe-mgmt-latest.cisco.com -p 8181
Password:

Welcome to the DevNet Sandbox for CSR1000v and IOS XE

The following programmability features are already enabled:
  - NETCONF
  - RESTCONF

Thanks for stopping by.

csr1000v-1#`

===========================

**Using JumpSSH**

`In [1]: from jumpssh import SSHSession

In [2]: jump_session = SSHSession('ios-xe-mgmt-latest.cisco.com', username='developer', port=8181, password='C1sco12345').open()
---------------------------------------------------------------------------
AuthenticationException                   Traceback (most recent call last)
/usr/local/lib/python3.6/site-packages/jumpssh/session.py in open(self, retry, retry_interval)
    159                 # connect to the host
--> 160                 self.ssh_client.connect(**self.extra_parameters)
    161

/usr/local/lib/python3.6/site-packages/paramiko/client.py in connect(self, hostname, port, username, password, pkey, key_filename, timeout, allow_agent, look_for_keys, compress, sock, gss_auth, gss_kex, gss_deleg_creds, gss_host, banner_timeout, auth_timeout, gss_trust_dns, passphrase, disabled_algorithms)
    445             t.gss_host,
--> 446             passphrase,
    447         )

/usr/local/lib/python3.6/site-packages/paramiko/client.py in _auth(self, username, password, pkey, key_filenames, allow_agent, look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host, passphrase)
    763         if saved_exception is not None:
--> 764             raise saved_exception
    765         raise SSHException("No authentication methods available")

/usr/local/lib/python3.6/site-packages/paramiko/client.py in _auth(self, username, password, pkey, key_filenames, allow_agent, look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host, passphrase)
    750             try:
--> 751                 self._transport.auth_password(username, password)
    752                 return

/usr/local/lib/python3.6/site-packages/paramiko/transport.py in auth_password(self, username, password, event, fallback)
   1508         try:
-> 1509             return self.auth_handler.wait_for_response(my_event)
   1510         except BadAuthenticationType as e:

/usr/local/lib/python3.6/site-packages/paramiko/auth_handler.py in wait_for_response(self, event)
    235                     e = AuthenticationException("Authentication failed.")
--> 236                 raise e
    237             if event.is_set():

AuthenticationException: Authentication failed.

The above exception was the direct cause of the following exception:

ConnectionError                           Traceback (most recent call last)
<ipython-input-2-ad8ab7881a93> in <module>
----> 1 jump_session = SSHSession('ios-xe-mgmt-latest.cisco.com', username='developer', port=8181, password='C1sco12345').open()

/usr/local/lib/python3.6/site-packages/jumpssh/session.py in open(self, retry, retry_interval)
    172                 else:
    173                     raise exception.ConnectionError("Unable to connect to '%s:%s' with user '%s'"
--> 174                                                     % (self.host, self.port, self.username), original_exception=ex)
    175
    176         # Get the client's transport

ConnectionError: Unable to connect to 'ios-xe-mgmt-latest.cisco.com:8181' with user 'developer': Authentication failed.

In [3]:`

===========================

**I can connect to the same box using Paramiko.**

`In [10]: import paramiko

In [11]: ssh = paramiko.SSHClient()
    ...: ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ...: ssh.connect('ios-xe-mgmt-latest.cisco.com', port=8181, username='developer', password='C1sco12345', look_for_keys=False,allow_agent=False)
    ...: remote = ssh.invoke_shell()

In [12]: remote.send('sh run | i hostname\n')
Out[12]: 20

In [13]: output = remote.recv(65000)
    ...: print(output)
b'\r\nWelcome to the DevNet Sandbox for CSR1000v and IOS XE\r\n\r\nThe following programmability features are already enabled:\r\n  - NETCONF\r\n  - RESTCONF\r\n\r\nThanks for stopping by.\r\n\r\n\r\n\r\ncsr1000v-1#sh run | i hostname\r\nhostname csr1000v-1\r\ncsr1000v-1#'

In [14]:`

**Comment by t-cas** [comment]
Hi @netengpy,

If manual authentication using `paramiko` is working, it should work the same using `jumpssh` as long as you use same input parameters.
In your case, when using directly `paramiko`, your are passing additional parameters `look_for_keys=False, allow_agent=False`, you should try to do the same when calling SSHSession
 
    jump_session = SSHSession(
        'ios-xe-mgmt-latest.cisco.com', 
        username='developer', 
        port=8181, 
        password='C1sco12345',
        look_for_keys=False, 
        allow_agent=False,
    ).open()
    remote = jump_session.ssh_client.invoke_shell()
    remote.send('sh run | i hostname\n')
    ...

This is the only difference I can see, could you try that ?

**Comment by netengpy** [comment]
Hi t-cas
thanks a lot for your reply.
yes that worked .. I tried that the other day but didn't work .. 
anyhow .. it works :)
thanks for sharing!
