### ISSUE TITLE
gateway_session.get_remote_session not respecting 'timeout' parameter

### ISSUE THREAD

**Issue by eladavron** [AmadeusITGroup/JumpSSH#120]
When executing the command "gateway_session.get_remote_session" with a timeout set, if the address is not correct the timeout parameter will not be respected.
Example code:
```py
gateway_session = SSHSession(
    gateway,
    gw_username,
    password=gw_password,
    timeout=5,
).open()  # This actually DOES respect timeout

session = gateway_session.get_remote_session(
    hostname,
    username,
    password=password,
    timeout=5,
)  # This does not respect timeout, for example if the hostname is wrong.
```
The issue seems to be in session.py in line 139:
```py
ssh_channel = self.proxy_transport.open_channel("direct-tcpip", dest_addr, local_addr)
```
This tries to open a channel, but doesn't pass the timeout parameter, so it is not passed to the command (which does support it).

I think "timeout" is an important enough parameter to exist outside of kwargs, or at the very least observed and passed to open_channel.

**Comment by t-cas** [comment]
Thanks @eladavron for catching that issue and highlighting the faulty line.
And I agree with you `timeout` parameter is worth to be added outside of kwargs

**Comment by t-cas** [comment]
Delivered in release [1.6.4](https://github.com/AmadeusITGroup/JumpSSH/releases/tag/1.6.4)
