### ISSUE TITLE
Executing a long running command through Jumpssh

### ISSUE THREAD

**Issue by mohammedtalo** [AmadeusITGroup/JumpSSH#136]
Hi,

Really appreciate your support on this.

I want to execute a command or a task however this command or task is different from Router to another Router. Some Router take 2 to 3 minutes and other around 5 minutes. i am using time.sleep(300) to overcome this  but it is not sufficient or pythonic.

Is there something to add to make jumpssh code below to make it do the task.

from jumpssh import SSHSession
import paramiko
import time

server_session = SSHSession(hostname, username=username, password='password').open()

switch_session = server_session.get_remote_session(hostname, username=name, password=password)
channel = switch_session.ssh_transport.open_session()
channel.get_pty()
channel.invoke_shell()
channel.send("some long command\n")  
time.sleep(300)  
output = channel.recv(65535)
print(output)  
server_session.close()
switch_session.close()

**Comment by t-cas** [comment]
Hi @mohammedtalo,

why are you not using directly the `run_cmd` or `get_cmd_output` methods, if you don't specify any timeout in input it will just wait for the command to end

    output = switch_session.get_cmd_output("some long command")
    print(output)

**Comment by mohammedtalo** [comment]
Hi @t-cas 

Actually i can't use  get_cmd_output because the router that i am connected too does not support this method. it is Alcatel Router.

**Comment by t-cas** [comment]
Here, unfortunately you have no structured information to indicate if your command is completed, the only way I see is to read received data until you get an expected value or pattern from `channel.recv` (See example of such loop in #144 )
