### ISSUE TITLE
Run a command with input data, got "paramiko.ssh_exception.AuthenticationException: Unable to connect to SSH agent"

### ISSUE THREAD

**Issue by jufei** [AmadeusITGroup/JumpSSH#139]
Hi:
   I use jumpssh to access my devices.
   First, it is ok to execute some simple command on remote host, like:

cpe_session = SSHSession('10.108.183.134', 'root', port=2201, password='Si8a&2vV9').open()
lines = cpe_session.run_cmd(cmd=['ps|grep ssh|grep root@local'], silent=False, continuous_output=True)

All above code works fine.

Now I need to execute a command that may need to enter password, like:

command = 'ssh -N -f -L 0.0.0.0:2301:169.254.0.1:23 root@localhost'
lines = cpe_session.run_cmd(cmd=[command], silent=False, continuous_output=True,
    input_data={'(y/n)':'y',
                'password:': 'Si8a&2vV9'})

This time, I got error:

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/site-packages/paramiko/agent.py", line 122, in run
    raise AuthenticationException("Unable to connect to SSH agent")
paramiko.ssh_exception.AuthenticationException: Unable to connect to SSH agent

I checked the code and comments the session.py, if I comment the line 302, like below, the error disappear.
 
#paramiko.agent.AgentRequestHandler(channel)

Would you please help to check this issue?

Thanks in advance.

**Comment by t-cas** [comment]
Hi @jufei,

it seems to be a bug but I have few questions to confirm it:

- do you have an agent running locally and some keys forwarded ?
- is it still working if you check for presence of ssh agent, modifying locally session.py with code:
  ```
  if paramiko.agent.Agent().get_keys():
       paramiko.agent.AgentRequestHandler(channel)
  ```

Thanks

**Comment by jufei** [comment]
hi, t-cas:
    Thanks for your response.
     I think I does not run agent locally, would you please tell me how to verify it? I use Centos 7.

    And yes, after change the session.py with your code, it is ok now.

Thanks.

**Comment by t-cas** [comment]
Thank for your quick answer.

to check if you have a running agent locally, simply run `ssh-add -l` and if you get
* "Error connecting to agent" (and exit code 2) => no agent running
* "The agent has no identities." (and exit code 1) => agent running but without any key loaded
* a list of keys (and exit code 0) => agent running with keys just displayed 

but if my code is working it confirms you don't have a running agent locally, I will submit a patch with that fix.

**Comment by jufei** [comment]
``` bash
[root@runner_132 work]# ssh-add -l
Could not open a connection to your authentication agent.
[root@runner_132 work]# 
```

Thanks and I will wait for your new version.

**Comment by t-cas** [comment]
Delivered in release [1.6.4](https://github.com/AmadeusITGroup/JumpSSH/releases/tag/1.6.4)
