### ISSUE TITLE
Output of Jump-ssh  is not getting all receiving  inputs from remote client 

### ISSUE THREAD

**Issue by ornitorenk** [AmadeusITGroup/JumpSSH#144]
Hi,

As you can see below, when I run below command, I am not able to get response of the command which I sent ?
Do you have any idea?

server_session = SSHSession('xxxx','zzzz',password='yyyy')
switch_session = server_session.get_remote_session('aaa', 'xxx', password = 'xxxx')
channel = switch_session.ssh_transport.open_session()
channel.get_pty()
channel.invoke_shell()
channel.send('show port\n')
output = channel.recv(1024)
print(output)

**Output of the script;**
b'\r\n\r\nWelcome to ISAM\r\nlast login : 20/08/20 18:39:33\r\n'

**Output of the command**
=================================================================
Ports on NT
=================================================================
Port          Admin Link Port    Cfg  Oper LAG/ Port Port Port
Id            State      State   MTU  MTU  Bndl Mode Encp Type
-----------------------------------------------------------------
nt:vp:1       Up    Yes  Up      1518 1518    - accs dotq vport
nt:mc:1       Up    Yes  Up      1518 1518    - accs dotq vport

=================================================================
Ports on NT-A
=================================================================
Port          Admin Link Port    Cfg  Oper LAG/ Port Port Port
Id            State      State   MTU  MTU  Bndl Mode Encp Type
-----------------------------------------------------------------

**Comment by t-cas** [comment]
Hi @ornitorenk,

`channel.recv(maxBytes)` is like reading a socket and just reads whatever data was sent from the remote server, not exceeding maxBytes.
It is commonly used in a loop until you get the piece of data that you are waiting for, this is why here you only got the first chunk of data sent by your remote server.

**Comment by ornitorenk** [comment]
thanks @t-cas   for the kind support. I've tried different bytes however it did not help:(

Actually, I've modified my code as per your feedback for the issue regarding Alcatel jumpssh. That's why, I try to use  channel.send as per your recommendation.
 _https://github.com/AmadeusITGroup/JumpSSH/issues/110#issuecomment-616194925_

I tried;
....
channel.invoke_shell()
output = switch_session.get_cmd_output("show  software-mngt version etsi  | match exact:isam\r")
print(output)      

or
.....

channel.invoke_shell()
output = switch_session.run_cmd("show  software-mngt version etsi  | match exact:isam\r")
print(output)      


**Error**
ChannelException: ChannelException(2, 'Connect failed')

I've faced above Error. Do you have any other recommendation to overcome from my problem?

**Comment by ornitorenk** [comment]
I could not find effective solution but I have a workaround as below.

```
from jumpssh import SSHSession
import time

server_session = SSHSession('10.239.XXX.XXX','XXXX',password='XXXX')
switch_session = server_session.get_remote_session('10.117.XXX.XX', 'XXXX', password = 'XXXXX')
channel = switch_session.ssh_transport.open_session()
channel.get_pty()
channel.invoke_shell()
channel.send('show port\n')
count=0
while True:
    if not channel.recv_ready():
        count=count+1
        print(count)
        print("*** Channel not ready for reading.")
        time.sleep(1)
        if count==5 :
            break
        continue
        
    data_chunk = channel.recv(1024)
    if len(data_chunk)== 0:
        print("*** Connection terminated")
        break
    else:
        print(f" {data_chunk.decode('utf-8')}")

```
