### ISSUE TITLE
Troublesome 'package.json' access at runtime in frozen applications

### ISSUE THREAD

**Issue by malversoft** [AmadeusITGroup/JumpSSH#152]
When using a Python frozen module (for example building an executable with PyInstaller), by default the builder only includes the Python bytecodes. So only that bytecodes are available when the module is imported at runtime.

But the JumpSSH package unconditionally reads the `package.json` file at runtime, just to get the package version.

For this reason JumpSSH can never be used as-is in a frozen Python executable. It requires to dive into the frozen applications builder and create specific hooks to include all JumpSSH files.

It would be a great help if the package simply specifies the version value in the code, so no data files are needed at runtime:
`
__version__ = "1.6.4"
`

Thanks in advance. And thanks for your good work.

**Comment by t-cas** [comment]
Hi @malversoft,

I fully agree with you, this design has been done few years ago and I think having version in python file would save some issues like yours.

**Comment by securenotebook** [comment]
Was banging my head against a wall for two days on this one. 

Great app, please let me when you resolve.  In the meantime is there any manual workarounds?

**Comment by t-cas** [comment]
delivered in #167 and is part of [jumpssh release 1.6.5](https://github.com/AmadeusITGroup/JumpSSH/releases/tag/1.6.5)
