### ISSUE TITLE
How to execute multiple commands on remote host

### ISSUE THREAD

**Issue by darkleo27** [AmadeusITGroup/JumpSSH#163]
Hi !!
Using library 'jumpssh'. I'd like to know how to get the output with different commands on remote session.

`result = remote_session.run_cmd('show version | in Pro')
                print(result.output)`
and for example, adding another command like 'show inter brief' on the same remote host.

I hope you can help me!

Thanks

**Comment by t-cas** [comment]
Hi @darkleo27,

you can use `run_cmd` as many times as you want on a given `SSHSession` instance as long as it is still open, so in your case

     for command in ["show version | in Pro", "show inter brief"]:
         print(remote_session.run_cmd(command).output)

hope that helps !

**Comment by darkleo27** [comment]
> Hi @darkleo27,
> 
> you can use `run_cmd` as many times as you want on a given `SSHSession` instance as long as it is still open, so in your case
> 
> ```
>  for command in ["show version | in Pro", "show inter brief"]:
>      print(remote_session.run_cmd(command).output)
> ```
> 
> hope that helps !

Hi !!! thanks for answering me !!! it helped me a lot !!!
