### ISSUE TITLE
Can jumpssh supports parallel ssh connections to different hosts once the jump ssh connection is established ? 

### ISSUE THREAD

**Issue by rakikulkarni** [AmadeusITGroup/JumpSSH#164]
I would like to multithread ssh connection with the single instance of jump server connection, is it supported?

**Comment by t-cas** [comment]
Hi @rakikulkarni,

yes this is supported, you have to open the jump session instance first and pass it to your threads, then each of your thread can open a new remote session to a dedicated server behind the jump server, simply calling `get_remote_session`.
