### ISSUE TITLE
Private key file is encrypted

### ISSUE THREAD

**Issue by AlexKrimi** [AmadeusITGroup/JumpSSH#40]
i have ed25519 private key, i need to use it to connect to jumpserver, but SSHSession init method does not seem to accept paramiko.Ed25519Key.from_private_key_file object, how to connect to jump server in this situation?

**Comment by t-cas** [comment]
Indeed SSHSession init does not support directly type `paramiko.pkey.PKey` in input today but if you called the method `from_private_key_file` if guess you have your private key file locally and in that case you can just use parameter `private_key_file` which is a local path to a private key file.
Another alternative if you use an SSH agent is to add this key to your agent, it will be used automatically by SSHSession when trying to connect
Would that work for you ?

**Comment by t-cas** [comment]
@AlexKrimi any news ? Does my answer work for you ?
