### ISSUE TITLE
Ability to use any parameter of paramiko.client.SSHClient.connect in SSHSession

### ISSUE THREAD

**Issue by t-cas** [AmadeusITGroup/JumpSSH#43]
Today each parameter of `paramiko.client.SSHClient.connect` must be explicitely declared in `jumpssh.SSHSession` init to be usable with paramiko connect
Purpose of this ticket is to add wilcard parameter to `SSHSession` and transmit all parameters with proper name to underlying paramiko api

**Comment by drax2gma** [comment]
This feature would be very nice to have. My scenario needs something like this:
- trying to login to the destination server with key. 
- key not exists
- give the user an option to log in with username and password
- at this point I need to pass the 'look_for_keys' parameter to Paramiko.

Thanks. ;)

**Comment by t-cas** [comment]
delivered in release [1.5.1](https://github.com/AmadeusITGroup/JumpSSH/releases/tag/1.5.1)
