### ISSUE TITLE
Sending hash fail

### ISSUE THREAD

**Issue by tiix95** [AmadeusITGroup/JumpSSH#50]
Hello,

I use this script to configure new users on remote linux boxes. I generate my password and sha512 hash locally and then send it via session.run_cmd : 

**Generated password :**
mv!T09Z9vO!Cd3fSywZ+5koNUrtI5NXU!exsIw3_Pg@o17UxYIU?NHRjCMbxiOq!?u7aCiNhTfThuv?Y555R7ZdsL5IuB5ZpMp6y

**Generated hash :** $6$DCuUrE5U$dZkcgO10qlZVQeJRMrlWQSKG6forTa2qSKfLfSs.9ok4ZuniayOXuHORm50NWHOhmMrQJkyEdEYQekguoJJ860

```
ssh = SSHSession(server, username=username, password=password, port=port)
cmd = "useradd -G %s -p %s -m -c 'User1 Account' -s /bin/bash -U %s" % (group, hash, user)
ssh.run_cmd("echo {} >> /tmp/a".format(h), username="root", timeout=10, retry=1, retry_interval=1)
```

**Output :**
```
# cat /tmp/a
.9ok4ZuniayOXuHORm50NWHOhmMrQJkyEdEYQekguoJJ860
```

If you want to test : 

```
def pw_gen(size):
    chars = string.ascii_letters + string.digits + string.punctuation
    return ''.join(random.choice(chars) for _ in range(size))
```
```
def sha512_crypt(password, salt=None, rounds=None):
    if salt is None:
        rand = random.SystemRandom()
        salt = ''.join([rand.choice(string.ascii_letters + string.digits)
                        for _ in range(8)])

    prefix = '$6$'
    if rounds is not None:
        rounds = max(1000, min(999999999, rounds or 5000))
        prefix += 'rounds={0}$'.format(rounds)

    return crypt.crypt(password, prefix + salt)
```

Thanks for your help !

**Comment by t-cas** [comment]
Hello @tiix95,

Thanks for the detailed explanation and the code sample to reproduce easily the issue !

First, you need to add single quotes around your hash.

Then indeed, when specifying `username` parameter, full command is run with shell and so specific shell characters (like '$' in your case)  must be escaped before giving them to `run_cmd`. 
As this is occurring only when specifying `username` parameter, it is true that this would deserve a specific note in the documentation.

This code works for me:

    escaped_hash = hash.replace('$', '\$')
    ssh.run_cmd("echo '{}' >> /tmp/a".format(escaped_hash), username="root")

Tell me if you still have issues.

**Comment by tiix95** [comment]
Hello,

I already tested with quotes and it didn't work, but I added the escaped characters and it works perfectly.
Thank you very much for your quick answer !
