### ISSUE TITLE
jumpssh 'get' fails if the remote file is binary.  It is wrong to assume the files to get are text files 

### ISSUE THREAD

**Issue by pshaobow** [AmadeusITGroup/JumpSSH#51]
jump.SSHSession.get function uses the following codes to get a remote file and the write to a local file:
    with open(local_path, mode='w') as local_file:
            with sftp_client.file(copy_path) as remote_file:
                     local_file.write(remote_file.read().decode('utf-8'))
When the remote file is in binary format such as PCAP file, it fails at the decode('utf-8').
The following should work for binary file:
   with open(local_path, mode='wb') as local_file:
            with sftp_client.file(copy_path) as remote_file:
                     local_file.write(remote_file.read())
A file format argument may be added to distinguish the ascii/text from bin (binary) type.

**Comment by t-cas** [comment]
Indeed thanks for catching that @pshaobow !
I will work on the fix

**Comment by t-cas** [comment]
fix delivered in release [1.6.1](https://github.com/AmadeusITGroup/JumpSSH/releases/tag/1.6.1)
