### ISSUE TITLE
Unable to connect to {IP} with user ‘rooot’: ‘str’ has no attribute ‘open_channel’

### ISSUE THREAD

**Issue by jeffparkermodhd** [AmadeusITGroup/JumpSSH#64]
Please help I am working on a project and I can’t get any other ssh python module to work with my raspberry pi model 3 b+

**Comment by t-cas** [comment]
Could you provide some information so that we can investigate:
* versions of python + python packages  (at least jumpssh and paramiko or output of `pip list`)
* code sample producing this error
* full exception stacktrace (not just error message)

Thanks

**Comment by jeffparkermodhd** [comment]
I am new to such module and I do not know if i can connect to my iPad (jialbroke) ssh wise utilizing such module if not... my apologies I sincerely apologize for such mistake. But if the case is that I can utilize this module for such connection please inform me how. I thought you could utilize it for this but I went on to your guys pypi page and I was confused when I did not see any local examples so I apologize if this is not what such module is for. Please accept my apology.

**Comment by jeffparkermodhd** [comment]
I am new to such module and I do not know if i can connect to my iPad (jialbroke) ssh wise utilizing such module if not... my apologies I sincerely apologize for such mistake. But if the case is that I can utilize this module for such connection please inform me how. I thought you could utilize it for this but I went on to your guys pypi page and I was confused when I did not see any local examples so I apologize if this is not what such module is for. Please accept my apology.
