### ISSUE TITLE
how to use SU and password after creating a remote session

### ISSUE THREAD

**Issue by abirlal** [AmadeusITGroup/JumpSSH#72]
Hi team,
pleas help me to use su command with password using interactive password prompt in  remote 
session.

I have tried below approach.  but not woring. please help.
gateway_session = SSHSession(hostname1, username1, password=password1).open()

remote_session = gateway_session.get_remote_session(hostname2,  username=username2, password=password2)
remote_session.is_active()
remote_session.run_cmd('su')

Thanks in advance.

**Comment by t-cas** [comment]
Hi @abirlal,

unfortunately you cannot use a simple `su` here as each command run with `run_cmd` is independent from the next call to `run_cmd` even when using the same `SSHSession` instance.

Then, if what you want is calling next commands as root, you don't need to use `su` and can use one of the following:
- `remote_session.run_cmd('<your command here>', username='root')`
- `remote_session.run_cmd('sudo <your command here>')`

Does that solve your issue ?

**Comment by vsachin094** [comment]
Any solution for this ??
