### ISSUE TITLE
JumpSSH Permission error

### ISSUE THREAD

**Issue by Yasinmohammed007** [AmadeusITGroup/JumpSSH#83]
Hi,

I am have remote Linux Machine, Which asks password everyTime you do something on it. For Ex:
i'm using JumpSh Module to create a file. I have tried using use_sudo as True/False as well, When use_sudo =True its waiting for the password. But not sure how to pass them.

+++++++++++++++++++++++++++++++++++++++++++++++++++
gateway_session = SSHSession(controller_ip,args.user_name,port=port, password=pwd).open()
print("Hello")
print(gateway_session.file('/etc/resolv.conf', content='nameserver 10.220.220.228', permissions=777, use_sudo=True ))
+++++++++++++++++++++++++++++++++++++++++++++++++++++
gives back the below output
+++++++++++++++++++++

hello
None
Traceback (most recent call last):
  File "C:/Users/503144060/PycharmProjects/python-ilorest-library-master/examples/Redfish/test.py", line 82, in <module>
    check()
  File "C:/Users/503144060/PycharmProjects/python-ilorest-library-master/examples/Redfish/test.py", line 80, in check
    print(gateway_session.file('/etc/resolv.conf', content='nameserver 10.220.220.228',permissions=777,use_sudo=False))
  File "C:\Users\503144060\AppData\Roaming\Python\Python37\site-packages\jumpssh\session.py", line 699, in file
    with sftp_client.file(copy_path, mode='w+') as remote_file:
  File "C:\Users\503144060\AppData\Roaming\Python\Python37\site-packages\paramiko\sftp_client.py", line 372, in open
    t, msg = self._request(CMD_OPEN, filename, imode, attrblock)
  File "C:\Users\503144060\AppData\Roaming\Python\Python37\site-packages\paramiko\sftp_client.py", line 813, in _request
    return self._read_response(num)
  File "C:\Users\503144060\AppData\Roaming\Python\Python37\site-packages\paramiko\sftp_client.py", line 865, in _read_response
    self._convert_status(msg)
  File "C:\Users\503144060\AppData\Roaming\Python\Python37\site-packages\paramiko\sftp_client.py", line 896, in _convert_status
    raise IOError(errno.EACCES, text)
PermissionError: [Errno 13] Permission denied

+++++++++++++++++++++

**Comment by t-cas** [comment]
Hello @Yasinmohammed007,

to overwrite `/etc/resolv.conf` file you generally need root permissions.

If you current user is already `root`,  you don't need use_sudo as you are already root it should work fine.

Here, I guess that's not the case for you, so you need to set `use_sudo=True`.
Then depending on the setup of the remote server, it may indeed request a password, this is unfortunately not supported today by jumpssh `file` method.

As a workaround, and if you already have root access on the remote server, you can manually disable sudo password this remote server by editing  sudoers file with  `sudo visudo` and using this line for your user:
`your_username ALL=(ALL) NOPASSWD:ALL`, it will unblock you issue.

**Comment by Yasinmohammed007** [comment]
Hi @t-cas Thibaud, Thanks for replying on this.

Exactly, as you said, i Don't have root access, your suggestion is good. 
"your_username ALL=(ALL) NOPASSWD:ALL" , But i dont want to do it. 

How ever i've got the answer that JumpSSH doesn't support this passing password Feature. 

Would like to know, If Dev Team would consider this and add this feature to the code. Any idea what other modules i can use to solve the problem i've quoted.

**Comment by t-cas** [comment]
In fact, after a bit more thinking,  this behavior is already supported in jumpssh but on the more generic `run_cmd` method, so you can do it with jumpssh, it will  just require an additional command.
Something like the following should work:
      
    # create file in temporary path
    gateway_session.file('/tmp/resolv.conf', content='nameserver 10.220.220.228')

    # move it in final destination, send sudo password when needed
    gateway_session.run_cmd(
      'sudo mv /tmp/resolv.conf /etc/resolv.conf',
      input_data={'password': '<sudo_password_here>'},
    )

Note that you may need to adjust the key of `input_data` dictionary to match what is displayed when sudo password is requested. 

This is clearly a feature that could be added directly as part of `file` method to avoid this extra steps, I will create a dedicated ticket for that.

Tell me if it works fine for you.
