### ISSUE TITLE
get access to the prompts on remote session

### ISSUE THREAD

**Issue by aditya-hub** [AmadeusITGroup/JumpSSH#87]
While running commands on a remote session using get_cmd_output, my command intermittently prompts for password. Is there a way to provide inputs for such prompts.

**Comment by t-cas** [comment]
yes, you can provide input parameter `input_data`, which is a dictionary where 
* key is a pattern to match the prompt line
* value is the value to send when pattern is matched (here, your password)

for example:

    mysession.get_cmd_output('<a_command>', input_data={'password': '<your_password>'})
