### ISSUE TITLE
Accessing the remote session instance more than once throws Authentication Failure

### ISSUE THREAD

**Issue by nitinbhat** [AmadeusITGroup/JumpSSH#90]
I am trying to access a remote server through jump server and it throws below error if i use the instance second time. It works in first call. It happens with few servers.

from jumpssh import SSHSession
jump_server = SSHSession('<IP>,'<Username>',password='<Password>').open()
remote_server = jump_server.get_remote_session(<IP>,'<Username>',password='<Password>')
print(remote_server.get_cmd_output('pwd'))<<WORKS
print(remote_server.get_cmd_output('pwd'))<<<<<<<<<<This throws below error

Failure: Authenticator could not validate SESS TOKEN <1k0xvdl5nxnv33chp4hj8yw0c71lwwu657at4q61lkvuvhh36vjr> of instance <1021216> status <59>

**Comment by t-cas** [comment]
This scenario is normally working without any particular setup in jumpssh.
The issue may come from a restriction on remote ssh server setup which only supports one channel per connection/transport.

You can check status of the SSHSession with 

    print(remote_server.is_active())

you can also try forcing a clean re-connection to remote server explicitly calling 

    remote_server.close()
    remote_server.open()
