### ISSUE TITLE
Despite closing the remote session, commands can be executed in the host

### ISSUE THREAD

**Issue by BharthishAthreya** [AmadeusITGroup/JumpSSH#95]
I wanted to run few commands on the host by opening the session through jumpssh and close once it is done. But even after closing the session im able to run the command through same session which was closed. 
 
Please see the below screen shot for further information. 

![jumpssh_issue](https://user-images.githubusercontent.com/15611058/75543118-23eaf500-5a47-11ea-80e7-abd9129fa9f2.PNG)

**Comment by t-cas** [comment]
Your call to `close()` worked well, you can see it wit the print of `is_active()`.
It's simply that any function (like `get_command_output`) that requires an open session to work, will try first to transparently open (or re-open) the current session for you.
So in fact, in most of the cases you don't need to explicitly call `open()` as it will be done for you when you really need it.

**Comment by BharthishAthreya** [comment]
Thanks a lot for the reply. So closing the session at the end of our functions will do, right? Thanks once again

**Comment by t-cas** [comment]
yes, it will work, just to give you more details, you have several possibilities to ensure sessions are closed, depending on when you want them to be closed:
* close it explicitly when needed
* use context manager so it will be closed automatically at the end of block
* don't do anything, it will be closed automatically when SSHSession instance is garbage collected
